---
- name: "update local apt repo"
  become: true
  apt:
    update_cache: yes

- name: "upgrade apt packages"
  become: true
  apt:
    upgrade: true
  
- name: "Remove unrequired dependencies"
  become: true
  apt:
    autoremove: true
  

- name: "Install nodejs and npm"
  become: true
  shell:  |
    curl -fsSL https://deb.nodesource.com/setup_lts.x | sudo -E bash -
    sudo apt install -y nodejs
    sudo npm install --global n
    sudo n 13.8.0
        
- name: "install pm2"
  become: true
  npm:
    name: pm2
    global: yes